name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/pythonApps
            rm -R Klasifikasi-Bunga-Anggrek-CNN
            git clone https://github.com/haxorsprogramming/Klasifikasi-Bunga-Anggrek-CNN
            # mv 4D-Integrasi/ 4d/
            cp .env_Klasifikasi_Bunga_Anggrek_CNN Klasifikasi-Bunga-Anggrek-CNN/.env
            chown -R www-data:www-data Klasifikasi-Bunga-Anggrek-CNN
            chmod -R 755 Klasifikasi-Bunga-Anggrek-CNN
            cd Klasifikasi-Bunga-Anggrek-CNN
            # composer update
            # php artisan migrate:refresh --seed
            exit